//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenderPayGap.Models.GPGEntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GpgDBEntities : DbContext
    {
        public GpgDBEntities()
            : base("name=GpgDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<GroupPermissions> GroupPermissions { get; set; }
        public virtual DbSet<Organisation> Organisation { get; set; }
        public virtual DbSet<OrganisationAddress> OrganisationAddress { get; set; }
        public virtual DbSet<OrganisationFiles> OrganisationFiles { get; set; }
        public virtual DbSet<OrganisationGPGReturns> OrganisationGPGReturns { get; set; }
        public virtual DbSet<OrganisationStatuses> OrganisationStatuses { get; set; }
        public virtual DbSet<Return> Return { get; set; }
        public virtual DbSet<ReturnHit> ReturnHit { get; set; }
        public virtual DbSet<ReturnStatuses> ReturnStatuses { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserGroups> UserGroups { get; set; }
        public virtual DbSet<UserStatuses> UserStatuses { get; set; }
    }
}
