//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenderPayGap.Models.GpgEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnHit
    {
        public long ReturnHitId { get; set; }
        public long ReturnId { get; set; }
        public long ByAccountId { get; set; }
        public Nullable<byte> HitType { get; set; }
        public string Source { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual Return Return { get; set; }
    }
}
