//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenderPayGap.Models.GPGEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroups
    {
        public long UserId { get; set; }
        public long GroupId { get; set; }
        public string Created { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
