//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenderPayGap.Models.GPGEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStatuses
    {
        public long UserStatusId { get; set; }
        public long UserId { get; set; }
        public byte StatusId { get; set; }
        public System.DateTime StatusDate { get; set; }
        public string StatusMessage { get; set; }
        public Nullable<long> ByUserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
