//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenderPayGap.Models.GpgDatabase
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Threading;

    public partial class GpgDatabase : DbContext
    {
        public GpgDatabase()
            : base("GpgDatabase")
        {
        }
        public static GpgDatabase Default = new GpgDatabase();

        public virtual DbSet<Organisation> Organisation { get; set; }
        public virtual DbSet<OrganisationAddress> OrganisationAddress { get; set; }
        public virtual DbSet<OrganisationStatus> OrganisationStatus { get; set; }
        public virtual DbSet<Return> Return { get; set; }
        public virtual DbSet<ReturnStatus> ReturnStatus { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserStatus> UserStatuses { get; set; }
        public virtual DbSet<UserOrganisation> UserOrganisations { get; set; }
        public virtual DbSet<UserToken> UserTokens { get; set; }

        public static int Truncate(params string[] tables)
        {
            List<string> target = new List<string>();

            if (tables == null || tables.Length == 0)
            {
                target = GetTableList(GpgDatabase.Default);
            }
            else
            {
                target.AddRange(tables);
            }

            int result = 0;
            for (int i = 0; i < 10; i++)
            {
                result = 0;
                foreach (var table in target)
                {
                    try
                    {
                        GpgDatabase.Default.Database.ExecuteSqlCommand(string.Format("TRUNCATE TABLE [{0}]", table));
                        result++;
                    }
                    catch (Exception ex)
                    {
                        try
                        {
                            GpgDatabase.Default.Database.ExecuteSqlCommand(string.Format("DELETE [{0}]", table));
                            result++;

                            try
                            {
                                GpgDatabase.Default.Database.ExecuteSqlCommand(string.Format("DBCC CHECKIDENT ([{0}], RESEED, 1)", table));
                            }
                            catch (Exception ex1)
                            {

                            }
                        }
                        catch (Exception ex2)
                        {

                        }
                    }
                }
                if (result == target.Count()) break;
                if (result == 10) throw new Exception("Unable to truncate all tables");
            }
            GpgDatabase.Default.SaveChanges();
            return result;
        }

        public static List<string> GetTableList(DbContext db)
        {
            List<string> tableNames = db.Database.SqlQuery<string>("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME NOT LIKE '%Migration%' AND TABLE_NAME NOT LIKE 'AspNet%'").ToList();
            return tableNames;
            var type = db.GetType();

            return db.GetType().GetProperties()
                .Where(x => x.PropertyType.Name == "DbSet`1")
                .Select(x => x.Name).ToList();
        }

        public static void RefreshAll()
        {
            Default = new GpgDatabase();
        }

        public override int SaveChanges()
        {
            int c = 0;
            retry:
            try
            {
                return base.SaveChanges();
            }
            catch (Exception ex)
            {
                c++;
                Thread.Sleep(1000);
                if (c<10)goto retry;
                throw;
            }
        }
    }
}
