//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpgDB.Models.GpgDatabase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Organisation
    {
        public Organisation()
        {
            this.OrganisationAddresses = new HashSet<OrganisationAddress>();
            this.OrganisationStatuses = new HashSet<OrganisationStatus>();
            this.Returns = new HashSet<Return>();
        }


        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long OrganisationId { get; set; }

        [MaxLength(10)]
        public string PrivateSectorReference { get; set; }

        [MaxLength(10)]
        public string PublicSectorReference { get; set; }

        [Required(AllowEmptyStrings = false)]
        [MaxLength(100), MinLength(5)]
        [Index]
        public string OrganisationName { get; set; }

        [Required]
        [Column("SectorTypeId")]
        [Index]
        public SectorTypes SectorType { get; set; }

        [Required]
        [Column("CurrentStatusID")]
        public OrganisationStatuses CurrentStatus { get; set; }

        [Required]
        public System.DateTime CurrentStatusDate { get; set; } = DateTime.Now;

        [MaxLength(255)]
        public string CurrentStatusDetails { get; set; }

        [Required]
        public System.DateTime Created { get; set; } = DateTime.Now;

        [Required]
        public System.DateTime Modified { get; set; } = DateTime.Now;

        public virtual ICollection<OrganisationAddress> OrganisationAddresses { get; set; }

        public virtual ICollection<OrganisationStatus> OrganisationStatuses { get; set; }

        public virtual ICollection<Return> Returns { get; set; }
    }
}
