//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpgDB.Models.GpgDatabase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ReturnStatus
    {
        public ReturnStatus()
        {
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long ReturnStatusId { get; set; }

        [Required]
        public long ReturnId { get; set; }

        [Required]
        [Column("StatusId")]
        public ReturnStatuses Status { get; set; }

        [Required]
        [Index]
        public System.DateTime  StatusDate { get; set; } = DateTime.Now;

        [MaxLength(255)]
        public string StatusMessage { get; set; }

        [Required]
        public long ByUserId { get; set; }

        [ForeignKey("ReturnId")]
        public virtual Return Return { get; set; }

        [ForeignKey("UserId")]
        public virtual User ByUser { get; set; }
    }
}
