//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpgDB.Models.GpgDatabase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Return
    {
        public Return()
        {
            this.ReturnStatuses = new HashSet<ReturnStatus>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long ReturnId { get; set; }

        [Required]
        [Index]

        public long OrganisationId { get; set; }

        [Required]
        [Index]
        public System.DateTime AccountingDate { get; set; }

        [Required]
        public decimal DiffMeanHourlyPayPercent { get; set; }

        [Required]
        public decimal DiffMedianHourlyPercent { get; set; }

        [Required]
        public decimal DiffMeanBonusPercent { get; set; }

        [Required]
        public decimal DiffMedianBonusPercent { get; set; }

        [Required]
        public decimal MaleMedianBonusPayPercent { get; set; }

        [Required]
        public decimal FemaleMedianBonusPayPercent { get; set; }

        [Required]
        public decimal MaleLowerPayBand { get; set; }

        [Required]
        public decimal FemaleLowerPayBand { get; set; }

        [Required]
        public decimal MaleMiddlePayBand { get; set; }

        [Required]
        public decimal FemaleMiddlePayBand { get; set; }

        [Required]
        public decimal MaleUpperPayBand { get; set; }

        [Required]
        public decimal FemaleUpperPayBand { get; set; }

        [Required]
        public decimal MaleUpperQuartilePayBand { get; set; }

        [Required]
        public decimal FemaleUpperQuartilePayBand { get; set; }

        [MaxLength(255)]
        public string CompanyLinkToGPGInfo { get; set; }

        [Required]
        [Column("CurrentStatusId")]
        public ReturnStatuses CurrentStatus { get; set; }

        [Required]
        public System.DateTime CurrentStatusDate { get; set; } = DateTime.Now;

        [MaxLength(255)]
        public string CurrentStatusDetails { get; set; }

        [Required]
        public System.DateTime Created { get; set; } = DateTime.Now;

        [Required]
        public System.DateTime Modified { get; set; } = DateTime.Now;

        [Required(AllowEmptyStrings = false)]
        [MaxLength(100)]
        public string JobTitle { get; set; }

        [Required(AllowEmptyStrings = false)]
        [MaxLength(50)]
        public string FirstName { get; set; }

        [Required(AllowEmptyStrings = false)]
        [MaxLength(50)]
        public string LastName { get; set; }

        public virtual ICollection<ReturnStatus> ReturnStatuses { get; set; }

        [ForeignKey("OrganisationId")]
        public virtual Organisation Organisation { get; set; }

    }
}
