//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpgDB.Models.GpgDatabase
{
    using Extensions;
    using IdentityServer3.Core;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using System.Security.Claims;
    using System.Security.Principal;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserStatuses = new HashSet<UserStatus>();
            this.Organisations = new HashSet<Organisation>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long UserId { get; set; }
        [Required(AllowEmptyStrings = false)]
        [MaxLength(50)]
        public string JobTitle { get; set; }

        [Required(AllowEmptyStrings = false)]
        [MaxLength(50)]
        public string Firstname { get; set; }

        [Required(AllowEmptyStrings = false)]
        [MaxLength(50)]
        public string Lastname { get; set; }

        [Required(AllowEmptyStrings = false)]
        [MaxLength(255)]
        [Index]
        public string EmailAddress { get; set; }

        [Required(AllowEmptyStrings = false)]
        [MaxLength(100),MinLength(8)]
        public string Password { get; set; }

        [Required(AllowEmptyStrings = false)]
        [MaxLength(255)]
        public string EmailVerifyCode { get; set; }

        public Nullable<System.DateTime> EmailVerifySendDate { get; set; }

        public Nullable<System.DateTime> EmailVerifiedDate { get; set; }

        [Column("CurrentStatusId")]
        [Required]
        public UserStatuses CurrentStatus { get; set; }

        [Required]
        public System.DateTime CurrentStatusDate { get; set; } = DateTime.Now;

        [MaxLength(255)]
        public string CurrentStatusDetails { get; set; }

        [Required]
        public System.DateTime Created { get; set; } = DateTime.Now;

        [Required]
        public System.DateTime Modified { get; set; } = DateTime.Now;
 
        public virtual ICollection<Organisation> Organisations { get; set; }

        public virtual ICollection<UserStatus> UserStatuses { get; set; }

        [NotMapped]
        public string Fullname {
            get
            {
                return (Firstname + " " + Lastname).TrimI();
            }
        }


    }
}
