//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenderPayGap.Models.gpgsqlAzureEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPermissions
    {
        public long GroupId { get; set; }
        public byte PermissionId { get; set; }
        public byte GroupPermissionsID { get; set; }
    }
}
