//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenderPayGap.Models.gpgsqlAzureEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organisation()
        {
            this.OrganisationFiles = new HashSet<OrganisationFiles>();
            this.OrganisationStatuses = new HashSet<OrganisationStatuses>();
            this.ReturnHit = new HashSet<ReturnHit>();
            this.OrganisationGPGReturns = new HashSet<OrganisationGPGReturns>();
        }
    
        public long OrganisationId { get; set; }
        public long GroupId { get; set; }
        public string URN { get; set; }
        public string OrganisationName { get; set; }
        public string OrganisationType { get; set; }
        public string OrganisationPhase { get; set; }
        public string OrganisationPolicy { get; set; }
        public string OrganisationDescription { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> Population { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public string CurrentStatus { get; set; }
        public System.DateTime CurrentStatusDate { get; set; }
        public string CurrentStatusDetails { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual OrganisationAddress OrganisationAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganisationFiles> OrganisationFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganisationStatuses> OrganisationStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnHit> ReturnHit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganisationGPGReturns> OrganisationGPGReturns { get; set; }
    }
}
