//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenderPayGap.Models.gpgsqlAzureEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnStatuses
    {
        public long ReturnStatusId { get; set; }
        public long ReturnId { get; set; }
        public byte StatusId { get; set; }
        public System.DateTime StatusDate { get; set; }
        public string StatusMessage { get; set; }
        public Nullable<long> ByUserId { get; set; }
    
        public virtual Return Return { get; set; }
        public virtual User User { get; set; }
    }
}
