//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenderPayGap.Models.gpgsqlAzureEntityModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Return
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Return()
        {
            this.OrganisationGPGReturns = new HashSet<OrganisationGPGReturns>();
            this.ReturnHit = new HashSet<ReturnHit>();
            this.ReturnStatuses = new HashSet<ReturnStatuses>();
        }
    
        public long ReturnId { get; set; }

        [Display(Name = "*Enter the difference in mean hourly rate")]
        public decimal DiffMeanHourlyPayPercent { get; set; }

        [Display(Name = "*Enter the difference in median hourly rate")]
        public decimal DiffMedianHourlyPercent { get; set; }

        [Display(Name = "*Enter the difference in mean bonus pay")]
        public decimal DiffMeanBonusPercent { get; set; }

        [Display(Name = "*Enter the difference in median bonus pay")]
        public decimal DiffMedianBonusPercent { get; set; }

        [Display(Name = "* Males who received bonus pay %")]
        public decimal MaleMedianBonusPayPercent { get; set; }

        [Display(Name = "*Females who received bonus pay %")]
        public decimal FemaleMedianBonusPayPercent { get; set; }

        [Display(Name = "*Male")]
        public decimal MaleLowerPayBand { get; set; }

        [Display(Name = "*Female")]
        public decimal FemaleLowerPayBand { get; set; }

        [Display(Name = "*Male")]
        public decimal MaleMiddlePayBand { get; set; }

        [Display(Name = "*Female")]
        public decimal FemaleMiddlePayBand { get; set; }

        [Display(Name = "*Male")]
        public decimal MaleUpperPayBand { get; set; }

        [Display(Name = "*Female")]
        public decimal FemaleUpperPayBand { get; set; }

        [Display(Name = "*Male")]
        public decimal MaleUpperQuartilePayBand { get; set; }

        [Display(Name = "*Female")]
        public decimal FemaleUpperQuartilePayBand { get; set; }

        [Display(Name = "*Enter the web address (URL) for the gender pay gap information published on your organisation’s website. The person with responsibility for gender pay gap reporting in your organisation will have this.")]
        public string CompanyLinkToGPGInfo { get; set; }
        public string CurrentStatus { get; set; }
        public Nullable<System.DateTime> CurrentStatusDate { get; set; }
        public string CurrentStatusDetails { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganisationGPGReturns> OrganisationGPGReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnHit> ReturnHit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnStatuses> ReturnStatuses { get; set; }
    }
}
