//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenderPayGap
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GpgDBEntities : DbContext
    {
        public GpgDBEntities()
            : base("name=GpgDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<OrganisationAddress> OrganisationAddresses { get; set; }
        public virtual DbSet<OrganisationFile> OrganisationFiles { get; set; }
        public virtual DbSet<OrganisationGPGReturn> OrganisationGPGReturns { get; set; }
        public virtual DbSet<OrganisationStatus> OrganisationStatuses { get; set; }
        public virtual DbSet<Return> Returns { get; set; }
        public virtual DbSet<ReturnHit> ReturnHits { get; set; }
        public virtual DbSet<ReturnStatus> ReturnStatuses { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserStatus> UserStatuses { get; set; }
        public virtual DbSet<AuthToken> AuthTokens { get; set; }
    }
}
